FROM php:7.4.28-fpm-alpine3.15
LABEL autor="Carlos Carpintero" version="1.0"
RUN apk add nano zip git
COPY ./config/after.sh /home
RUN chmod +x /home/after.sh && \
    sh /home/after.sh
RUN apk --update --no-cache add autoconf g++ make && \
    pecl install -f xdebug && \
    apk del --purge autoconf g++ make
RUN docker-php-ext-enable xdebug
RUN echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so" >> /usr/local/etc/php/php.ini-development && \
    cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini && \
    rm /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini-production && \
    echo "xdebug.mode=debug,trace,develop" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.discover_client_host=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.client_host=172.20.0.3" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.client_port=9003" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.idekey=docker" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
WORKDIR /public_html
