version: '3.7'
services:
  server:
    container_name: server
    build:
      context: ./config/Dockerfiles/nginx/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/Escritorio/volumenes/app_data:/public_html
    ports:
      - 80:80
    networks:
      - mi-red
  app:
    container_name: app
    build:
      context: ./config/Dockerfiles/php/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/Escritorio/volumenes/app_data:/public_html
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
    networks:
      - mi-red
networks:
      mi-red:
